# Generated by Django 3.2.4 on 2021-06-22 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
